[14.0][ADD] shift: New module
OCA/shift-planning pull request #8
Opened 2024-10-16 15:16 UTC by chienandalu

WIP

A novel approach for employees shifts

![Peek 16-10-2024 17-14](https://github.com/user-attachments/assets/2eca896c-d46e-432f-a8ba-8c552771db50)

cc @Tecnativa TT50623

2024-10-16 15:40 UTC, carmenbianca commented
@chienandalu Hi! This repository is the eventual (hopeful) new home of the shift modules at https://github.com/beescoop/Obeesdoo/tree/16.0. But the cleaning up and moving of those modules to the OCA has been delayed due to the bane of all projects—lack of time.

I have not yet reviewed the code submitted (but the gif looks very cool). My initial thought/observation is that there is a namespace collision for the module name `shift`.

Can you give me more context for the business need of this module? With this context, I can talk to the team at Coop IT Easy, and we can maybe cooperate on either (A.) finally cleaning up `shift` in the linked repository to fulfil both our needs, or (B.) migrating to your WIP module by merging functionalities from the linked repository.

Thanks!

2024-10-16 18:36 UTC, pedrobaeza commented
This one is a generic system for shifts. Yours is oriented just for cooperators, so I think it may be renamed to` shift_cooperator` or `cooperator_shift` when coming to OCA, don't you think?

2024-10-17 08:57 UTC, remytms commented
Yes our module is for managing shift for benevolent, yours is for employee. That's the difference. Managing benevolent or employee does not have the same constrain. But anyway, this module is very interesting.

2024-10-17 09:53 UTC, pedrobaeza commented
Yeah, and yours is thought for being each person who set their shift, and this one is for a manager to plan the shifts.

@chienandalu what about renaming this to `hr_shift`?

2024-10-17 10:01 UTC, chienandalu commented
> @chienandalu what about renaming this to `hr_shift`?

I'm ok with it :smile:

2024-10-17 10:02 UTC, pedrobaeza commented
Let's go with it then.

2024-10-17 14:19 UTC, carmenbianca commented
Fantastic. Please ping again when the module is ready for review :)

2025-01-09 18:31 UTC, cvinh commented
Runboat is stuck... can you check it for us to review please ?

2025-01-10 09:08 UTC, chienandalu commented
> Runboat is stuck... can you check it for us to review please ?

I can push again to reload it but without this merged, it isn't going to be functional: https://github.com/OCA/OCB/pull/1261

2025-01-10 09:38 UTC, pedrobaeza commented
I have merged the OCB patch, so push to rebuild. I'm a bit worried about the compatibility though. Is this needed in all the versions?

2025-01-10 09:46 UTC, chienandalu commented
> I have merged the OCB patch, so push to rebuild. I'm a bit worried about the compatibility though. Is this needed in all the versions?

It is at least in v15

2025-01-10 09:51 UTC, pedrobaeza commented
Then we need to do the patch here in this module.

2025-01-10 10:54 UTC, chienandalu commented
> Then we need to do the patch here in this module.

Ok, I got to make it. So now it can work even without the patch.

2025-01-10 16:59 UTC, cvinh requested changes
Quick review to make runboat usable out of the box

2025-01-10 16:59 UTC, cvinh commented on hr_shift/__manifest__.py
> +    "category": "Marketing",
```suggestion
    "category": "Human Resources/Shifts",
    "application": True,
```

2025-01-10 16:59 UTC, cvinh commented on hr_shift/__manifest__.py
> +    "depends": ["hr", "base_sparse_field"],
```suggestion
    "depends": ["hr"],
```

2025-01-10 16:59 UTC, cvinh commented on hr_shift/__manifest__.py
> +    "data": [
It's worth to have demo data, at least 2 or 3 employees with shift_planning=True and 2 shift_template (morning and afternoon) would be enough

2025-01-10 16:59 UTC, cvinh commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
```suggestion
        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id",
        default= True,
```

2025-01-10 16:59 UTC, cvinh commented on hr_shift/views/shift_planning_views.xml
> +    <record id="shift_planning_shift_action" model="ir.actions.act_window">
Maybe menuitems and actions should be in hr_views.xml

2025-01-10 16:59 UTC, cvinh commented on hr_shift/wizards/shift_planning_wizard_views.xml
> +    <record id="shift_planning_wizard_action" model="ir.actions.act_window">
This button should be invisible if there is no planning yet... or it fails with python error 'no week'

2025-01-17 08:17 UTC, cvinh commented
Dear @chienandalu did you see why we could not use hr_shift here https://github.com/OCA/hr/issues/1432
Maybe there would be something to do with merging those 2 different approaches that leed to the same goal...

2025-01-17 08:31 UTC, chienandalu commented on hr_shift/__manifest__.py
> +    "depends": ["hr", "base_sparse_field"],
Why? I need that dependency for the Serialized fields I'm using

2025-01-17 08:32 UTC, chienandalu commented on hr_shift/__manifest__.py
> +    "data": [
I'll do it :)

2025-01-17 08:34 UTC, cvinh commented on hr_shift/__manifest__.py
> +    "depends": ["hr", "base_sparse_field"],
Oh I thought you did the move not to depend on it ... My bad you were talking on OCB's commit

2025-01-17 08:35 UTC, chienandalu commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
You mean it for the `shift_planning` field I guess. I our case studies there's a mix of employees doing shifts (like factory workers) and with fixed work hours (office workers)

2025-01-17 08:35 UTC, chienandalu commented on hr_shift/wizards/shift_planning_wizard_views.xml
> +    <record id="shift_planning_wizard_action" model="ir.actions.act_window">
I'll take a look

2025-01-17 08:41 UTC, cvinh commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
> You mean it for the `shift_planning` field I guess. I our case studies there's a mix of employees doing shifts (like factory workers) and with fixed work hours (office workers)

Heu yes what I mean is that if you have 200 employees and you wish to install this module, it means you want at least to use hr shift stuff with at least most of the employees so it's easier to uncheck the employees that do not have hr shift than checking all the ~180 employees that use the shift

2025-01-17 08:47 UTC, cvinh commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
> You mean it for the `shift_planning` field I guess. I our case studies there's a mix of employees doing shifts (like factory workers) and with fixed work hours (office workers)

Well we have a use case here with factory workers as well. Usually they do not do a whole week morning and then a whole week afternoon... they do something like monday, tuesday morning, wednesday time off, thursday friday afternoon...
It can also be more complicated when some people work on weekend then they have time off the next week... and so on...
I think the worst case would be an international airline company or a ship company.... the more flexible we do the OCA module, the best it can fit to every use case...
We are ready to collaborate here, we have a real use case as well :-)

2025-01-17 08:49 UTC, chienandalu commented on hr_shift/__manifest__.py
> +    "depends": ["hr", "base_sparse_field"],
Yes, that was it. Now we don't depend on that patch. But serialized field hacks are extensively used in the kanban views to display and interact with the shifts info

2025-01-17 09:05 UTC, chienandalu commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
> Heu yes what I mean is that if you have 200 employees and you wish to install this module, it means you want at least to use hr shift stuff with at least most of the employees so it's easier to uncheck the employees that do not have hr shift than checking all the ~180 employees that use the shift

Yes... our ratio right now is like 50/50 or 40/60... so there's no clear default in our case...

The trick we use (and teach to customers :)) for that initial setup is to set the first employee, the go to the kanban view and group by that field and start dragging to the needed ones to the right column


>  they do something like monday, tuesday morning, wednesday time off, thursday friday afternoon...

I think it could be achieved extending the shift templates or adding an extra layer to group the shifts and use them as proper templates.

> It can also be more complicated when some people work on weekend then they have time off the next week... and so on...

The customers using this right now come from an Excel sheet solution to handle the shifts :sweat_smile: They manually copy-pasted to which shift every employee had to make that week, and every week a responsible was doing that on hand...

I mean, lots of those small decisions can't be really automated. For the time-off, well, you'll see that employee isn't available for the next week, as the panel will tell so.

> I think the worst case would be an international airline company or a ship company.... the more flexible we do the OCA module, the best it can fit to every use case...

The most flexible a case is, the more manually handled it tends to be, so I guess that's already covered :smile:

2025-01-17 09:08 UTC, cvinh commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
> Yes... our ratio right now is like 50/50 or 40/60... so there's no clear default in our case...
> 
> The trick we use (and teach to customers :)) for that initial setup is to set the first employee, the go to the kanban view and group by that field and start dragging to the needed ones to the right column

Ok fair enough

2025-01-17 09:09 UTC, pedrobaeza commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
Maybe it can be set that the kanban view shows all the groups, no matter if having already an employee or not, similar to what is done on CRM.

2025-01-17 09:13 UTC, cvinh commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
> I mean, lots of those small decisions can't be really automated. For the time-off, well, you'll see that employee isn't available for the next week, as the panel will tell so.

Of course ! There is theorical planning and real planning when people change their schedules between them and go to the hr saying 'it's ok it swapped my shift with my friend'.
I think it can be solved by generating real shifts (as calendar.events or holidays) that can be swapped or changed independantly from templates that would be here only to 'generate' theorical shifts... Wdyt ?

2025-01-17 09:15 UTC, chienandalu commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
Yeah, that's easy to do (it's done with the shifts). No sure if it will work with booleans thou

2025-01-17 09:17 UTC, chienandalu commented on hr_shift/views/shift_planning_views.xml
> +    <record id="shift_planning_shift_action" model="ir.actions.act_window">
That's a formal preference :). My personal one is to stick them to the model views avoiding later manifest data loading issues when a dependent data isn't loaded yet...

2025-01-17 09:22 UTC, cvinh commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
> I think it could be achieved extending the shift templates or adding an extra layer to group the shifts and use them as proper templates.

Extending shift template like we select the day and in front the 'time start' and 'time end'
Or more complicated, a shift template on 3 weeks as we have here indeed :
1st week
Monday : 7:00-13:00
Tuesday : 7:00-13:00
Wednesday : time off
Thursday : 13:00-19:00
Friday : 13:00-19:00
Saturday : 7:00-13:00
Sunday : 8:30-12:30
2nd week
Monday : 13:00-19:00
Tuesday : 7:00-13:00
Wednesday : 7:00-13:00
Thursday : 13:00-19:00
Friday : 13:00-19:00
3rd week
Monday : 13:00-19:00
Tuesday : 7:00-13:00
Wednesday : 7:00-13:00
Thursday : 13:00-19:00
Friday : 07:00-13:00
And every employee does not have same planning according to their Job Position... or individually because that employee has special favor with the boss... that's real case with small companies in healthcare industry for example

2025-01-17 09:23 UTC, cvinh commented on hr_shift/views/shift_planning_views.xml
> +    <record id="shift_planning_shift_action" model="ir.actions.act_window">
> That's a formal preference :). My personal one is to stick them to the model views avoiding later manifest data loading issues when a dependent data isn't loaded yet...

Yes agreed it's unsignificant detail

2025-01-17 09:26 UTC, cvinh commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
> Yeah, that's easy to do (it's done with the shifts). No sure if it will work with booleans thou

Well I did not see it, I'm gonna dig again in shifts

2025-01-17 09:34 UTC, chienandalu commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
Oh, I meant the group expand thing. The swap shift feature isn't available. Odoo's EE planning tool has a wizard to do so and if I'm not wrong it can be done from the portal. A similar thing could be put in the roadmap (there's no need of the current scheme change, but those UIs are to be done...). Right now, only a responsible can swap it manually dragging from one column to another.

2025-01-17 09:35 UTC, cvinh commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
> Oh, I meant the group expand thing

Ok

2025-01-17 09:39 UTC, cvinh commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
> The swap shift feature isn't available. Odoo's EE planning tool has a wizard to do so and if I'm not wrong it can be done from the portal. A similar thing could be put in the roadmap (there's no need of the current scheme change, but those UIs are to be done...). Right now, only a responsible can swap it manually dragging from one column to another.

Oh I didn't mean the employees can swap themselves as they want.... I meant they come to see the hr manager and ask him to swap for them as they agree...
EE planning is not available for CE users so we must do a good OCA module. We can contribute and/or sponsor

2025-01-17 09:52 UTC, chienandalu commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
Yes, sure. I was mentioning it as a reference. It's always good to keep an eye on what the vendor does even if we don't agree with it :sweat_smile: 

Right now, a manager could just swap it dragging the employees shifts in the detailed view.

2025-01-17 10:11 UTC, cvinh commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
> Right now, a manager could just swap it dragging the employees shifts in the detailed view.

On the whole shift template I saw it... but on a single day only, it's not covered IMHO...

2025-01-17 11:11 UTC, chienandalu commented on hr_shift/models/hr_employee.py
> +        comodel_name="hr.shift.planning.line", compute="_compute_current_shift_id"
try this :slightly_smiling_face: 

![Peek 17-01-2025 12-08](https://github.com/user-attachments/assets/87bc3904-b588-43ad-85d0-345fda355f21)

And then in the week overall view you can spot there are differences by their color codes:

![image](https://github.com/user-attachments/assets/387ed4de-9868-4052-ab0f-5a5218cf0b9d)

2025-06-02 08:35 UTC, victoralmau approved these changes
Functional review OK

2025-06-02 21:51 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2025-06-02 21:54 UTC, merged